//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muhasebe {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Form1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form1() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Muhasebe.Form1", typeof(Form1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {X=17,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Point databaseDataSet_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("databaseDataSet.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {X=775,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Point firmalarBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("firmalarBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {X=947,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Point firmalarTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("firmalarTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {X=472,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Point gelirBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("gelirBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {X=626,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Point gelirTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("gelirTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {X=160,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Point giderBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("giderBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {X=319,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Point giderTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("giderTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {X=153,Y=56} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Point openFileDialog1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("openFileDialog1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {X=17,Y=56} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Point saveFileDialog1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("saveFileDialog1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Bitmap toolStrip1_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("toolStrip1.BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   {X=1113,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Point toolStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
